delete from wkf_triggers where wkf_triggers.instance_id in (select wkf_instance.id from wkf_instance where res_type in ('procurement.order','sale.order','account.invoice','stock.picking','purchase.order','account.voucher'));
delete from wkf_witm_trans where wkf_witm_trans.inst_id in (select wkf_instance.id from wkf_instance where res_type in ('procurement.order','sale.order','account.invoice','stock.picking','purchase.order','account.voucher'));
delete from wkf_workitem where wkf_workitem.inst_id in (select wkf_instance.id from wkf_instance where res_type in ('procurement.order','sale.order','account.invoice','stock.picking','purchase.order','account.voucher'));
delete from wkf_instance where res_type in ('procurement.order','sale.order','account.invoice','stock.picking','purchase.order','account.voucher');
delete from ir_attachment where res_model in ('procurement.order','sale.order','account.invoice','stock.picking','purchase.order','account.voucher','purchase.order.line');
delete from account_invoice;
delete from account_move;
delete from account_move_reconcile;
delete from account_invoice_line;
delete from account_invoice_tax;
delete from account_analytic_line;
delete from purchase_order;
delete from purchase_order_line;
delete from stock_move;
delete from stock_picking;
delete from stock_production_lot;
delete from stock_production_lot_revision;
delete from stock_move_history_ids;
delete from stock_inventory_line;
delete from stock_inventory_move_rel;
delete from stock_inventory;
delete from procurement_order;
delete from sale_order_line;
delete from sale_order;
delete from res_log;
delete from res_request;
delete from product_product where active=False;